name: Main workflow
on:
  push:
    branches:
      - main
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDKAdd commentMore actions
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Install Flyway
      run: |
        curl -L -o flyway-commandline.tar.gz "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/11.1.0/flyway-commandline-11.1.0-linux-x64.tar.gz"
        tar -xzf flyway-commandline.tar.gz
        sudo ln -s `pwd`/flyway-11.1.0/flyway /usr/local/bin/flyway
        
    - name: 🔍 Debug DB connection and permissions
      env:
        PGHOST: ${{ secrets.DB_HOST }}
        PGPORT: ${{ secrets.DB_PORT }}
        PGDATABASE: ${{ secrets.DB_NAME }}
        PGUSER: ${{ secrets.DB_USER }}
        PGPASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        echo "🔌 Проверка подключения к PostgreSQL..."
        psql -c "SELECT current_user, session_user;" || { echo "❌ Не удалось подключиться"; exit 1; }

        echo "✅ Подключение успешно."

        echo "🔍 Проверка прав на схему 'public'..."
        psql -c "
          SELECT n.nspname AS schema,
                r.rolname AS grantee,
                has_schema_privilege(r.rolname, n.nspname, 'USAGE') AS usage,
                has_schema_privilege(r.rolname, n.nspname, 'CREATE') AS create
          FROM pg_namespace n
          JOIN pg_roles r ON r.rolname = current_user
          WHERE n.nspname = 'public';
        "

        echo "📂 Проверка доступа к файловой системе миграций:"
        ls -la migrations || echo "⚠️ migrations не найдены!"


    - name: Run Flyway migrations
      env:
        FLYWAY_URL: "jdbc:postgresql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}"
        FLYWAY_USER: ${{ secrets.DB_USER }}
        FLYWAY_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: flyway migrate -locations=filesystem:migrations

    ### Этот шаг оставьте без изменений
    - name: Download and setup autotests binaries
      run: |
        wget -qO- cloud-services-engineer.gitlab.yandexcloud.net/practicum-cloud-services/dbops-autotests/-/package_files/1/download > dbopstest
        chmod +x ./dbopstest
        mv ./dbopstest /usr/local/bin/dbopstest

    ### Этот шаг оставьте без изменений
    - name: Test
      run: |
        dbopstest \
          -test.v \
          -host=${{ secrets.DB_HOST }} \
          -port=${{ secrets.DB_PORT }} \
          -user=${{ secrets.DB_USER }} \
          -password=${{ secrets.DB_PASSWORD }} \
          -db=${{ secrets.DB_NAME }}
